### ISSUE TITLE
Kindle edge documentation is not being generated

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails-docs-server#5]
I'm getting:

```
[2015-01-29 23:31:06 UTC] RAILS_VERSION="455e663" EDGE="1" rvm 2.2.0 do bundle _1.7.12_ exec rake guides:generate:kindle >/dev/null
Please `gem install kindlerb` and make sure you have `kindlegen` in your PATH
```

**Comment by fxn** [comment]
How strange, it's in the project _Gemfile_, I'll investigate.

**Comment by fxn** [comment]
The _Gemfile_ did not have the version of `kindlerb` fixed, and a few days ago the gem was upgraded. I have fixed the version in master, 4-2-stable, and 4-1-stable.

**Comment by fxn** [comment]
Looking good... thanks for the ticket man!

**Comment by rafaelfranca** [comment]
Cool! Thanks for fixing it.
